app:
  name: HitPipe
  port: ${APP_PORT:8080}
  env: ${APP_ENV:local}

postgres:
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  host: ${POSTGRES_HOST:postgres}
  port: ${POSTGRES_PORT:5432}
  db: ${POSTGRES_DB:postgres}
  ssl_mode: disable

logger:
  level: ${LOGGER_LEVEL:debug}
