app:
  name: "Hitpipe"
  env: "development"

postgres:
  user: "postgres"
  password: "${DB_PASSWORD}"
  host: "postgres"
  port: "5432"
  db_name: "users_db"
  ssl_mode: "disable"

  logger:
    level: debug